# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, cereal, conduit, conduitExtra, cryptohash, filepath
, httpConduit, liftedAsync, liftedBase, logging, mmorph
, monadControl, optparseApplicative, resourcet, stm, tar, temporary
, text, transformers, unorderedContainers
}:

cabal.mkDerivation (self: {
  pname = "simple-mirror";
  version = "0.1.0.0";
  src = builtins.filterSource (path: type: type != "unknown") ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [
    cereal conduit conduitExtra cryptohash filepath httpConduit
    liftedAsync liftedBase logging mmorph monadControl
    optparseApplicative resourcet stm tar temporary text transformers
    unorderedContainers
  ];
  meta = {
    homepage = "http://fpcomplete.com";
    description = "Simple mirroring utility for Hackage";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
